version: '3.8'


services:
  mssql:
    build: .
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./scripts:/scripts
    networks:
      - sqlserver_network
    entrypoint: ["/bin/bash", "-c", "mkdir -p /var/opt/mssql/backup && wget -q -O /var/opt/mssql/backup/AdventureWorks2022.bak https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorks2022.bak && /opt/mssql/bin/sqlservr & sleep 20 && until /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P YourStrong!Passw0rd -Q 'SELECT 1'; do sleep 5; done && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P YourStrong!Passw0rd -i /scripts/restore.sql && tail -f /dev/null"]

volumes:
  sqlserver_data:

networks:
  sqlserver_network:
    driver: bridge